### ISSUE TITLE
Noisy console

### ISSUE THREAD

**Issue by Minhir** [andypf/json-viewer#15]
Hi @andypf, thanks for creating such a great library!

I noticed there are a few `console` statements in the code. For example, there is `console.debug(error)` in the `isUrl` function. It doesn't provide any value to the library users and can add additional noise into console, increase bundle size and slightly impact performance.

What do you think about removing it? It's also possible to introduce `log` function, which works only with `NODE_ENV=development` flag.

**Comment by andypf** [comment]
@Minhir Thank you for the feedback! I’ll take a look at it.

**Comment by andypf** [comment]
fixed with #16

**Comment by cadgerfeast** [comment]
Hey @andypf,
Thanks a lot for fixing this one.
I see you bumped to `v2.1.7` with this fix though I can still find `console.debug` references on dist files and I do still get debug logs on validations. See https://www.[unpkg.com/@andypf/json-viewer@2.1.7/dist/cjs/index.js

Maybe the library was not built before publishing the new version?
